#!/bin/bash

cd
DOTPATH="${PWD}/.dotfiles"
GITHUB_URL="https://github.com/akiramtmt/dotfiles.git"

if which git ; then
  if [[ -d "$DOTPATH" ]] ; then
    cd ${DOTPATH}
    git pull
  else
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  fi
else
  sudo yum install -y git
  if [[ -d "$DOTPATH" ]] ; then
    cd ${DOTPATH}
    git pull
  else
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  fi
fi

cd ${DOTPATH}
for dotfile in .?*
do
  if [ $dotfile != '..' ] && [ $dotfile != '.git' ]
  then
    ln -fs "$PWD/$dotfile" $HOME
  fi
done

if [[ -d "dircolors" ]] ; then
  curl -o dircolors/dircolors.solarized-ansi-dark --create-dirs \
    -sSL https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark
  curl -o dircolors/dircolors.molokai --create-dirs \
    -sSL https://raw.githubusercontent.com/gcollura/dotfiles/master/dircolors/dircolors.molokai
fi

mkdir -p ~/.vim/autoload ~/.vim/colors ~/.vim/plugged
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +'PlugInstall --sync' +qa

pkg_installed=$(yum grouplist | sed '/^Installed Groups:/,$!d;/^Available Groups:/,$d;/^Installed Groups:/d;s/^[[:space:]]*//')
if echo ${pkg_installed}}|grep 'Development' > /dev/null; then
  :
else
  sudo yum groupinstall -y "Development Tools"
fi

if [[ -d ~/bin ]] ; then
  :
else
  mkdir -p ~/bin
fi
