#!/bin/bash

DOTPATH="${PWD}/.dotfiles"
GITHUB_URL="https://github.com/akiramtmt/dotfiles.git"

if which git ; then
  if [[ -d "$DOTPATH" ]] then
    cd ${DOTPATH}
    git pull
  else
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  fi
else
  sudo yum install -y git
  if [[ -d "$DOTPATH" ]] then
    cd ${DOTPATH}
    git pull
  else
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  fi
fi

cd ${DOTPATH}
for dotfile in .?*
do
  if [ $dotfile != '..' ] && [ $dotfile != '.git' ]
  then
    ln -fs "$PWD/$dotfile" $HOME
  fi
done

if [[ -d "dircolors" ]] ; then
  curl -o dircolors/dircolors.solarized-ansi-dark --create-dirs \
    -sSL https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.ansi-dark
  curl -o dircolors/dircolors.molokai --create-dirs \
    -sSL https://raw.githubusercontent.com/gcollura/dotfiles/master/dircolors/dircolors.molokai
fi

sudo yum groupinstall -y "Development Tools"

mkdir -p ~/.vim/autoload ~/.vim/colors ~/.vim/plugged
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#if [ -d ~/.vim/bundle ]
#then
#  cd ~/.vim/bundle/neobundle.vim
#  git pull
#  vim -u ~/.vimrc -i NONE -c "try | NeoBundleUpdate! | finally | q! | endtry" -e -s -V1
#else
#  mkdir -p ~/.vim/bundle
#  git clone https://github.com/Shougo/neobundle.vim ~/.vim/bundle/neobundle.vim
#  vim -u ~/.vimrc -i NONE -c "try | NeoBundleUpdate! | finally | q! | endtry" -e -s
#fi

vim +'PlugInstall --sync' +qa
